# Dissecando variável, mostre todas as informações possíveis sobre uma determinada variável.
a = input("Digite algo: ")
print("O tipo primitivo desse valor é: ", type(a))
print("Só tem espaços? ", a.isspace())
print("É um número?", a.isnumeric())
print("É alfabético?", a.isalpha())
print("É alfanumérico?", a.isalnum())
print("Está em maiúsculo?" , a.isupper())
print("Tá em minúsculo?", a.islower())
print("Tá com a primeira letra maiúscula?" , a.istitle)
